// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of sm_tb_sale_item_log table changes.
 */
public interface SmTbSaleItemLogListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a SmTbSaleItemLogBean record into the database.
     *
     * @param pObject the SmTbSaleItemLogBean that is about to be inserted
     */
    public void beforeInsert(SmTbSaleItemLogBean pObject) throws SQLException;


    /**
     * Invoked just after a SmTbSaleItemLogBean record is inserted in the database.
     *
     * @param pObject the SmTbSaleItemLogBean that was just inserted
     */
    public void afterInsert(SmTbSaleItemLogBean pObject) throws SQLException;


    /**
     * Invoked just before updating a SmTbSaleItemLogBean record in the database.
     *
     * @param pObject the SmTbSaleItemLogBean that is about to be updated
     */
    public void beforeUpdate(SmTbSaleItemLogBean pObject) throws SQLException;


    /**
     * Invoked just after updating a SmTbSaleItemLogBean record in the database.
     *
     * @param pObject the SmTbSaleItemLogBean that was just updated
     */
    public void afterUpdate(SmTbSaleItemLogBean pObject) throws SQLException;


// class+ 

// class- 
}
