// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.sql.*;
// imports+ 

// imports- 

/**
 * Handles database calls for the sm_tb_account_group table.
 */
public class SmTbAccountGroupManager
// extends+ 

// extends- 
{

    /**
     * Column role_type of type Types.VARCHAR mapped to String.
     */
    public static final int ID_ROLE_TYPE = 0;
    public static final int TYPE_ROLE_TYPE = Types.VARCHAR;
    public static final String NAME_ROLE_TYPE = "role_type";

    /**
     * Column user_id of type Types.DECIMAL mapped to Long.
     */
    public static final int ID_USER_ID = 1;
    public static final int TYPE_USER_ID = Types.DECIMAL;
    public static final String NAME_USER_ID = "user_id";

    /**
     * Column description of type Types.VARCHAR mapped to String.
     */
    public static final int ID_DESCRIPTION = 2;
    public static final int TYPE_DESCRIPTION = Types.VARCHAR;
    public static final String NAME_DESCRIPTION = "description";


    private static final String TABLE_NAME = "sm_tb_account_group";

    /**
     * Create an array of type string containing all the fields of the sm_tb_account_group table.
     */
    private static final String[] FIELD_NAMES =
    {
        "sm_tb_account_group.role_type"
        ,"sm_tb_account_group.user_id"
        ,"sm_tb_account_group.description"
    };

    /**
     * Field that contains the comma separated fields of the sm_tb_account_group table.
     */
    private static final String ALL_FIELDS = "sm_tb_account_group.role_type"
                            + ",sm_tb_account_group.user_id"
                            + ",sm_tb_account_group.description";

    private static SmTbAccountGroupManager singleton = new SmTbAccountGroupManager();

    /**
     * Get the SmTbAccountGroupManager singleton.
     *
     * @return SmTbAccountGroupManager
     */
    synchronized public static SmTbAccountGroupManager getInstance()
    {
        return singleton;
    }

    /**
     * Sets your own SmTbAccountGroupManager instance.
     <br>
     * This is optional, by default we provide it for you.
     */
    synchronized public static void setInstance(SmTbAccountGroupManager instance)
    {
        singleton = instance;
    }


    /**
     * Creates a new SmTbAccountGroupBean instance.
     *
     * @return the new SmTbAccountGroupBean
     */
    public SmTbAccountGroupBean createSmTbAccountGroupBean()
    {
        return new SmTbAccountGroupBean();
    }



    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from sm_tb_account_group.
     *
     * @return an array of SmTbAccountGroupManager pObject
     */
    //38
    public SmTbAccountGroupBean[] loadAll() throws SQLException
    {
        return loadAll(1, -1);
    }


    /**
     * Loads the given number of rows from sm_tb_account_group, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of SmTbAccountGroupManager pObject
     */
    //38.5
    public SmTbAccountGroupBean[] loadAll(int startRow, int numRows) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM sm_tb_account_group",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            return loadByPreparedStatement(ps, null, startRow, numRows);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of SmTbAccountGroupBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting SmTbAccountGroupBean table
     */
    //49
    public SmTbAccountGroupBean[] loadByWhere(String where) throws SQLException
    {
        return loadByWhere(where, null);
    }

    /**
     * Retrieves an array of SmTbAccountGroupBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param fieldList table of the field's associated constants
     * @return the resulting SmTbAccountGroupBean table
     */
    //51
    public SmTbAccountGroupBean[] loadByWhere(String where, int[] fieldList) throws SQLException
    {
        return loadByWhere(where, null, 1, -1);
    }

    /**
     * Retrieves an array of SmTbAccountGroupBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting SmTbAccountGroupBean table
     */
    //51.5
    public SmTbAccountGroupBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws SQLException
    {
        String sql = null;
        if(fieldList == null)
            sql = "select " + ALL_FIELDS + " from sm_tb_account_group " + where;
        else
        {
            StringBuffer buff = new StringBuffer(128);
            buff.append("select ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0)
                    buff.append(",");
                buff.append(FIELD_NAMES[fieldList[i]]);
            }
            buff.append(" from sm_tb_account_group ");
            buff.append(where);
            sql = buff.toString();
            buff = null;
        }
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        java.util.ArrayList v = null;
        try
        {
            c = getConnection();
            pStatement = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs =  pStatement.executeQuery(sql);
            v = new java.util.ArrayList();
            int count = 0;
            if (rs.absolute(startRow) && numRows!=0) {
                do
                {
                    if(fieldList == null)
                        v.add(decodeRow(rs));
                    else
                        v.add(decodeRow(rs, fieldList));
                    count++;
                } while ( (count<numRows||numRows<0) && rs.next() );
            }

            return (SmTbAccountGroupBean[])v.toArray(new SmTbAccountGroupBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); }
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
    }


    /**
     * Deletes all rows from sm_tb_account_group table.
     * @return the number of deleted rows.
     */
    public int deleteAll() throws SQLException
    {
        return deleteByWhere("");
    }


    /**
     * Deletes rows from the sm_tb_account_group table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     */
    public int deleteByWhere(String where) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = getConnection();
            String delByWhereSQL = "DELETE FROM sm_tb_account_group " + where;
            ps = c.prepareStatement(delByWhereSQL);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // SAVE
    ///////////////////////////////////////////////////////////////////////
    /**
     * Saves the SmTbAccountGroupBean pObject into the database.
     *
     * @param pObject the SmTbAccountGroupBean pObject to be saved
     */
    //100
    public SmTbAccountGroupBean save(SmTbAccountGroupBean pObject) throws SQLException
    {
        if (!pObject.isModified()) {
            return pObject; // should not we log something ?
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;

        try
        {
            c = getConnection();
            if (pObject.isNew())
            { // SAVE
                beforeInsert(pObject); // listener callback
                int _dirtyCount = 0;
                _sql = new StringBuffer("INSERT into sm_tb_account_group (");

                if (pObject.isRoleTypeModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("role_type");
                    _dirtyCount++;
                }

                if (pObject.isUserIdModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("user_id");
                    _dirtyCount++;
                }

                if (pObject.isDescriptionModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("description");
                    _dirtyCount++;
                }

                _sql.append(") values (");
                if(_dirtyCount > 0) {
                    _sql.append("?");
                    for(int i = 1; i < _dirtyCount; i++) {
                        _sql.append(",?");
                    }
                }
                _sql.append(")");

                ps = c.prepareStatement(_sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                _dirtyCount = 0;

                if (pObject.isRoleTypeModified()) {
                    ps.setString(++_dirtyCount, pObject.getRoleType());
                }

                if (pObject.isUserIdModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
                }

                if (pObject.isDescriptionModified()) {
                    ps.setString(++_dirtyCount, pObject.getDescription());
                }

                ps.executeUpdate();

                pObject.isNew(false);
                pObject.resetIsModified();
                afterInsert(pObject); // listener callback
            }
            else
            { // UPDATE

                beforeUpdate(pObject); // listener callback
                _sql = new StringBuffer("UPDATE sm_tb_account_group SET ");
                boolean useComma=false;

                if (pObject.isRoleTypeModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("role_type").append("=?");
                }

                if (pObject.isUserIdModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("user_id").append("=?");
                }

                if (pObject.isDescriptionModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("description").append("=?");
                }
                _sql.append("");
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                int _dirtyCount = 0;

                if (pObject.isRoleTypeModified()) {
                      ps.setString(++_dirtyCount, pObject.getRoleType());
                }

                if (pObject.isUserIdModified()) {
                      Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
                }

                if (pObject.isDescriptionModified()) {
                      ps.setString(++_dirtyCount, pObject.getDescription());
                }

                if (_dirtyCount == 0) {
                     return pObject;
                }

                ps.executeUpdate();
                pObject.resetIsModified();
                afterUpdate(pObject); // listener callback
            }

            return pObject;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    /**
     * Saves an array of SmTbAccountGroupBean pObjects into the database.
     *
     * @param pObjects the SmTbAccountGroupBean pObject table to be saved
     * @return the saved SmTbAccountGroupBean array.
     */
    //65
    public SmTbAccountGroupBean[] save(SmTbAccountGroupBean[] pObjects) throws SQLException
    {
        for (int iIndex = 0; iIndex < pObjects.length; iIndex ++){
            save(pObjects[iIndex]);
        }
        return pObjects;
    }



    ///////////////////////////////////////////////////////////////////////
    // USING TEMPLATE
    ///////////////////////////////////////////////////////////////////////
    /**
     * Loads a unique SmTbAccountGroupBean pObject from a template one giving a c
     *
     * @param pObject the SmTbAccountGroupBean pObject to look for
     * @return the pObject matching the template
     */
    //85
    public SmTbAccountGroupBean loadUniqueUsingTemplate(SmTbAccountGroupBean pObject) throws SQLException
    {
         SmTbAccountGroupBean[] pReturn = loadUsingTemplate(pObject);
         if (pReturn.length == 0)
             return null;
         if (pReturn.length > 1)
             throw new SQLException("More than one element !!");
         return pReturn[0];
     }

    /**
     * Loads an array of SmTbAccountGroupBean from a template one.
     *
     * @param pObject the SmTbAccountGroupBean template to look for
     * @return all the SmTbAccountGroupBean matching the template
     */
    //88
    public SmTbAccountGroupBean[] loadUsingTemplate(SmTbAccountGroupBean pObject) throws SQLException
    {
        return loadUsingTemplate(pObject, 1, -1);
    }
    /**
     * Loads an array of SmTbAccountGroupBean from a template one, given the start row and number of rows.
     *
     * @param pObject the SmTbAccountGroupBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the SmTbAccountGroupBean matching the template
     */
    //88.5
    public SmTbAccountGroupBean[] loadUsingTemplate(SmTbAccountGroupBean pObject, int startRow, int numRows) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer where = new StringBuffer("");
        StringBuffer _sql = new StringBuffer("SELECT " + ALL_FIELDS + " from sm_tb_account_group WHERE ");
        StringBuffer _sqlWhere = new StringBuffer("");
        try
        {
            int _dirtyCount = 0;

             if (pObject.isRoleTypeModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("role_type= ?");
             }

             if (pObject.isUserIdModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("user_id= ?");
             }

             if (pObject.isDescriptionModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("description= ?");
             }

             if (_dirtyCount == 0) {
                 throw new SQLException ("The pObject to look for is invalid : not initialized !");
             }
             _sql.append(_sqlWhere);
             c = getConnection();
             ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
             _dirtyCount = 0;

             if (pObject.isRoleTypeModified()) {
                 ps.setString(++_dirtyCount, pObject.getRoleType());
             }

             if (pObject.isUserIdModified()) {
                 Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
             }

             if (pObject.isDescriptionModified()) {
                 ps.setString(++_dirtyCount, pObject.getDescription());
             }

             ps.executeQuery();
             return loadByPreparedStatement(ps, null, startRow, numRows);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }
    /**
     * Deletes rows using a SmTbAccountGroupBean template.
     *
     * @param pObject the SmTbAccountGroupBean object(s) to be deleted
     * @return the number of deleted objects
     */
    //63
    public int deleteUsingTemplate(SmTbAccountGroupBean pObject) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            sql = new StringBuffer("DELETE FROM sm_tb_account_group WHERE ");
            int _dirtyAnd = 0;
            if (pObject.isRoleTypeInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("role_type").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isUserIdInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("user_id").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isDescriptionInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("description").append("=?");
                _dirtyAnd ++;
            }

            c = getConnection();
            ps = c.prepareStatement(sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            int _dirtyCount = 0;

            if (pObject.isRoleTypeInitialized()) {
                ps.setString(++_dirtyCount, pObject.getRoleType());
            }

            if (pObject.isUserIdInitialized()) {
                Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
            }

            if (pObject.isDescriptionInitialized()) {
                ps.setString(++_dirtyCount, pObject.getDescription());
            }

            int _rows = ps.executeUpdate();
            return _rows;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // COUNT
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the number of rows of the table sm_tb_account_group.
     *
     * @return the number of rows returned
     */
    //78
    public int countAll() throws SQLException
    {
        return countWhere("");
    }



    /**
     * Retrieves the number of rows of the table sm_tb_account_group with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     */
    public int countWhere(String where) throws SQLException
    {
        String sql = "select count(*) as MCOUNT from sm_tb_account_group " + where;
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = getConnection();
            pStatement = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs =  pStatement.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
       throw new SQLException("Error in countWhere");
    }

    /**
     * Retrieves the number of rows of the table sm_tb_account_group with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     */
    //82
    int countByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next())
                iReturn = rs.getInt("MCOUNT");
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(rs);
        }
       throw new SQLException("Error in countByPreparedStatement");
    }

    /**
     * Looks for the number of elements of a specific SmTbAccountGroupBean pObject given a c
     *
     * @param pObject the SmTbAccountGroupBean pObject to look for
     * @return the number of rows returned
     */
    //83
    public int countUsingTemplate(SmTbAccountGroupBean pObject) throws SQLException
    {
        StringBuffer where = new StringBuffer("");
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;
        StringBuffer _sqlWhere = null;

        try
        {
                _sql = new StringBuffer("SELECT count(*) as MCOUNT  from sm_tb_account_group WHERE ");
                _sqlWhere = new StringBuffer("");
                int _dirtyCount = 0;

                if (pObject.isRoleTypeModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("role_type= ?");
                }

                if (pObject.isUserIdModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("user_id= ?");
                }

                if (pObject.isDescriptionModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("description= ?");
                }

                if (_dirtyCount == 0)
                   throw new SQLException ("The pObject to look is unvalid : not initialized !");

                _sql.append(_sqlWhere);
                c = getConnection();
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                _dirtyCount = 0;

                if (pObject.isRoleTypeModified()) {
                    ps.setString(++_dirtyCount, pObject.getRoleType());
                }

                if (pObject.isUserIdModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
                }

                if (pObject.isDescriptionModified()) {
                    ps.setString(++_dirtyCount, pObject.getDescription());
                }

                return countByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // DECODE RESULT SET
    ///////////////////////////////////////////////////////////////////////
    /**
     * Transforms a ResultSet iterating on the sm_tb_account_group on a SmTbAccountGroupBean pObject.
     *
     * @param rs the ResultSet to be transformed
     * @return pObject resulting SmTbAccountGroupBean pObject
     */
    //72
    public SmTbAccountGroupBean decodeRow(ResultSet rs) throws SQLException
    {
        SmTbAccountGroupBean pObject = createSmTbAccountGroupBean();
        pObject.setRoleType(rs.getString(1));
        pObject.setUserId(Manager.getLong(rs, 2));
        pObject.setDescription(rs.getString(3));

        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    /**
     * Transforms a ResultSet iterating on the sm_tb_account_group table on a SmTbAccountGroupBean pObject according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return pObject resulting SmTbAccountGroupBean pObject
     */
    //73
    public SmTbAccountGroupBean decodeRow(ResultSet rs, int[] fieldList) throws SQLException
    {
        SmTbAccountGroupBean pObject = createSmTbAccountGroupBean();
        int pos = 0;
        for(int i = 0; i < fieldList.length; i++)
        {
            switch(fieldList[i]) {
                case ID_ROLE_TYPE:
                    ++pos;
                    pObject.setRoleType(rs.getString(pos));
                    break;
                case ID_USER_ID:
                    ++pos;
                    pObject.setUserId(Manager.getLong(rs, pos));
                    break;
                case ID_DESCRIPTION:
                    ++pos;
                    pObject.setDescription(rs.getString(pos));
                    break;
            }
        }
        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of SmTbAccountGroupBean
     */
    //41
    public SmTbAccountGroupBean[] loadByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        return loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of SmTbAccountGroupBean
     */
    public SmTbAccountGroupBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws SQLException
    {
        return loadByPreparedStatement(ps, fieldList, 1, -1);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of SmTbAccountGroupBean
     */
    //41.5
    public SmTbAccountGroupBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws SQLException
    {
        ResultSet rs =  null;
        java.util.ArrayList v =  null;
        try
        {
            rs =  ps.executeQuery();
            v = new java.util.ArrayList();
            int count = 0;
            if (rs.absolute(startRow) && numRows!=0) {
                do
                {
                    if(fieldList == null)
                        v.add(decodeRow(rs));
                    else
                        v.add(decodeRow(rs, fieldList));
                    count++;
                } while ( (count<numRows||numRows<0) && rs.next() );
            }
            return (SmTbAccountGroupBean[])v.toArray(new SmTbAccountGroupBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    ///////////////////////////////////////////////////////////////////////
    // LISTENER
    ///////////////////////////////////////////////////////////////////////
    private SmTbAccountGroupListener listener = null;

    /**
     * Registers a unique SmTbAccountGroupListener listener.
     */
    //66.5
    public void registerListener(SmTbAccountGroupListener listener) {
        this.listener = listener;
    }

    /**
     * Before the save of the SmTbAccountGroupBean pObject.
     *
     * @param pObject the SmTbAccountGroupBean pObject to be saved
     */
    //67
    void beforeInsert(SmTbAccountGroupBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeInsert(pObject);
    }

    /**
     * After the save of the SmTbAccountGroupBean pObject.
     *
     * @param pObject the SmTbAccountGroupBean pObject to be saved
     */
    //68
    void afterInsert(SmTbAccountGroupBean pObject) throws SQLException {
        if (listener != null)
            listener.afterInsert(pObject);
    }

    /**
     * Before the update of the SmTbAccountGroupBean pObject.
     *
     * @param pObject the SmTbAccountGroupBean pObject to be updated
     */
    //69
    void beforeUpdate(SmTbAccountGroupBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeUpdate(pObject);
    }

    /**
     * After the update of the SmTbAccountGroupBean pObject.
     *
     * @param pObject the SmTbAccountGroupBean pObject to be updated
     */
    //70
    void afterUpdate(SmTbAccountGroupBean pObject) throws SQLException {
        if (listener != null)
            listener.afterUpdate(pObject);
    }

    ///////////////////////////////////////////////////////////////////////
    // UTILS
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //2
    Manager getManager() {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    void freeConnection(Connection c) {
        getManager().releaseConnection(c); // back to pool
    }
    /**
     * Gets the connection.
     */
    Connection getConnection() throws SQLException {
        return getManager().getConnection();
    }

// class+ 

// class- 
}
