// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

// imports+ 

// imports- 

/**
 * SmVwAccountPaySumBean is a mapping of sm_vw_account_pay_sum Table.
*/
public class SmVwAccountPaySumBean
// extends+ 

// extends- 
{

    private Long paySum;
    private boolean paySum_is_modified = false;
    private boolean paySum_is_initialized = false;


    private Long userId;
    private boolean userId_is_modified = false;
    private boolean userId_is_initialized = false;

    private boolean _isNew = true;

    /**
     * Do not use this constructor directly, please use the factory method
     * available in the associated manager.
     */
    SmVwAccountPaySumBean()
    {
    }

    /**
     * Getter method for paySum.
     * <br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: sm_vw_account_pay_sum.pay_sum
     * <li>column size: 32
     * <li>jdbc type returned by the driver: Types.DECIMAL
     * </ul>
     *
     * @return the value of paySum
     */
    public Long getPaySum()
    {
        return paySum;
    }

    /**
     * Setter method for paySum.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to paySum
     */
    public void setPaySum(Long newVal) {
        if ((newVal != null && this.paySum != null && (newVal.compareTo(this.paySum) == 0)) ||
            (newVal == null && this.paySum == null && paySum_is_initialized)) {
            return;
        }
        this.paySum = newVal;
        paySum_is_modified = true;
        paySum_is_initialized = true;
    }

    /**
     * Setter method for paySum.
     * <br>
     * Convenient for those who do not want to deal with Objects for primary types.
     *
     * @param newVal the new value to be assigned to paySum
     */
    public void setPaySum(long newVal) {
        setPaySum(new Long(newVal));
    }

    /**
     * Determines if the paySum has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isPaySumModified() {
        return paySum_is_modified;
    }

    /**
     * Determines if the paySum has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isPaySumInitialized() {
        return paySum_is_initialized;
    }

    /**
     * Getter method for userId.
     * <br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: sm_vw_account_pay_sum.user_id
     * <li>comments: The payed user id.
     * <li>column size: 22
     * <li>jdbc type returned by the driver: Types.DECIMAL
     * </ul>
     *
     * @return the value of userId
     */
    public Long getUserId()
    {
        return userId;
    }

    /**
     * Setter method for userId.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to userId
     */
    public void setUserId(Long newVal) {
        if ((newVal != null && this.userId != null && (newVal.compareTo(this.userId) == 0)) ||
            (newVal == null && this.userId == null && userId_is_initialized)) {
            return;
        }
        this.userId = newVal;
        userId_is_modified = true;
        userId_is_initialized = true;
    }

    /**
     * Setter method for userId.
     * <br>
     * Convenient for those who do not want to deal with Objects for primary types.
     *
     * @param newVal the new value to be assigned to userId
     */
    public void setUserId(long newVal) {
        setUserId(new Long(newVal));
    }

    /**
     * Determines if the userId has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isUserIdModified() {
        return userId_is_modified;
    }

    /**
     * Determines if the userId has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isUserIdInitialized() {
        return userId_is_initialized;
    }

    /**
     * Determines if the current object is new.
     *
     * @return true if the current object is new, false if the object is not new
     */
    public boolean isNew() {
        return _isNew;
    }

    /**
     * Specifies to the object if it has been set as new.
     *
     * @param isNew the boolean value to be assigned to the isNew field
     */
    public void isNew(boolean isNew) {
        this._isNew = isNew;
    }

    /**
     * Determines if the object has been modified since the last time this method was called.
     * <br>
     * We can also determine if this object has ever been modified since its creation.
     *
     * @return true if the object has been modified, false if the object has not been modified
     */
    public boolean isModified() {
        return paySum_is_modified ||
		userId_is_modified;
    }

    /**
     * Resets the object modification status to 'not modified'.
     */
    public void resetIsModified() {
        paySum_is_modified = false;
        userId_is_modified = false;
    }

    /**
     * Copies the passed bean into the current bean.
     *
     * @param bean the bean to copy into the current bean
     */
    public void copy(SmVwAccountPaySumBean bean) {
        setPaySum(bean.getPaySum());
        setUserId(bean.getUserId());
    }

    /**
     * Returns the object string representation.
     *
     * @return the object as a string
     */
    public String toString() {
        return   "\n[sm_vw_account_pay_sum] "
                 + "\n - sm_vw_account_pay_sum.pay_sum = " + (paySum_is_initialized ? ("[" + (paySum == null ? null : paySum.toString()) + "]") : "not initialized") + ""
                 + "\n - sm_vw_account_pay_sum.user_id = " + (userId_is_initialized ? ("[" + (userId == null ? null : userId.toString()) + "]") : "not initialized") + ""
            ;
    }

// class+ 

// class- 
}
