// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the SmVwSaleSumBean objects.
 */
public class SmVwSaleSumComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for SmVwSaleSumComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new SmVwSaleSumComparator(SmVwSaleSumManager.ITEM_SEQ, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>SmVwSaleSumManager.ID_ITEM_SEQ
     *   <li>SmVwSaleSumManager.ID_SALE_TOTAL
     * </ul>
     */
    public SmVwSaleSumComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for SmVwSaleSumComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new SmVwSaleSumComparator(SmVwSaleSumManager.ITEM_SEQ, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>SmVwSaleSumManager.ID_ITEM_SEQ
     *   <li>SmVwSaleSumManager.ID_SALE_TOTAL
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public SmVwSaleSumComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        SmVwSaleSumBean b1 = (SmVwSaleSumBean)pObj1;
        SmVwSaleSumBean b2 = (SmVwSaleSumBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case SmVwSaleSumManager.ID_ITEM_SEQ:
                if (b1.getItemSeq() == null && b2.getItemSeq() != null) {
                    iReturn = -1;
                } else if (b1.getItemSeq() == null && b2.getItemSeq() == null) {
                    iReturn = 0;
                } else if (b1.getItemSeq() != null && b2.getItemSeq() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getItemSeq().compareTo(b2.getItemSeq());
                }
                break;
            case SmVwSaleSumManager.ID_SALE_TOTAL:
                if (b1.getSaleTotal() == null && b2.getSaleTotal() != null) {
                    iReturn = -1;
                } else if (b1.getSaleTotal() == null && b2.getSaleTotal() == null) {
                    iReturn = 0;
                } else if (b1.getSaleTotal() != null && b2.getSaleTotal() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getSaleTotal().compareTo(b2.getSaleTotal());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
