// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.sql.*;
// imports+ 

// imports- 

/**
 * Handles database calls for the sm_tb_account_pay table.
 */
public class SmTbAccountPayManager
// extends+ 

// extends- 
{

    /**
     * Column index of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_INDEX = 0;
    public static final int TYPE_INDEX = Types.INTEGER;
    public static final String NAME_INDEX = "index";

    /**
     * Column user_id of type Types.DECIMAL mapped to Long.
     */
    public static final int ID_USER_ID = 1;
    public static final int TYPE_USER_ID = Types.DECIMAL;
    public static final String NAME_USER_ID = "user_id";

    /**
     * Column payed of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_PAYED = 2;
    public static final int TYPE_PAYED = Types.INTEGER;
    public static final String NAME_PAYED = "payed";

    /**
     * Column create_date of type Types.TIMESTAMP mapped to java.util.Date.
     */
    public static final int ID_CREATE_DATE = 3;
    public static final int TYPE_CREATE_DATE = Types.TIMESTAMP;
    public static final String NAME_CREATE_DATE = "create_date";

    /**
     * Column create_user of type Types.DECIMAL mapped to Long.
     */
    public static final int ID_CREATE_USER = 4;
    public static final int TYPE_CREATE_USER = Types.DECIMAL;
    public static final String NAME_CREATE_USER = "create_user";

    /**
     * Column modify_date of type Types.TIMESTAMP mapped to java.util.Date.
     */
    public static final int ID_MODIFY_DATE = 5;
    public static final int TYPE_MODIFY_DATE = Types.TIMESTAMP;
    public static final String NAME_MODIFY_DATE = "modify_date";

    /**
     * Column modify_user of type Types.DECIMAL mapped to Long.
     */
    public static final int ID_MODIFY_USER = 6;
    public static final int TYPE_MODIFY_USER = Types.DECIMAL;
    public static final String NAME_MODIFY_USER = "modify_user";


    private static final String TABLE_NAME = "sm_tb_account_pay";

    /**
     * Create an array of type string containing all the fields of the sm_tb_account_pay table.
     */
    private static final String[] FIELD_NAMES =
    {
        "sm_tb_account_pay.index"
        ,"sm_tb_account_pay.user_id"
        ,"sm_tb_account_pay.payed"
        ,"sm_tb_account_pay.create_date"
        ,"sm_tb_account_pay.create_user"
        ,"sm_tb_account_pay.modify_date"
        ,"sm_tb_account_pay.modify_user"
    };

    /**
     * Field that contains the comma separated fields of the sm_tb_account_pay table.
     */
    private static final String ALL_FIELDS = "sm_tb_account_pay.index"
                            + ",sm_tb_account_pay.user_id"
                            + ",sm_tb_account_pay.payed"
                            + ",sm_tb_account_pay.create_date"
                            + ",sm_tb_account_pay.create_user"
                            + ",sm_tb_account_pay.modify_date"
                            + ",sm_tb_account_pay.modify_user";

    private static SmTbAccountPayManager singleton = new SmTbAccountPayManager();

    /**
     * Get the SmTbAccountPayManager singleton.
     *
     * @return SmTbAccountPayManager
     */
    synchronized public static SmTbAccountPayManager getInstance()
    {
        return singleton;
    }

    /**
     * Sets your own SmTbAccountPayManager instance.
     <br>
     * This is optional, by default we provide it for you.
     */
    synchronized public static void setInstance(SmTbAccountPayManager instance)
    {
        singleton = instance;
    }


    /**
     * Creates a new SmTbAccountPayBean instance.
     *
     * @return the new SmTbAccountPayBean
     */
    public SmTbAccountPayBean createSmTbAccountPayBean()
    {
        return new SmTbAccountPayBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a SmTbAccountPayBean from the sm_tb_account_pay using its key fields.
     *
     * @return a unique SmTbAccountPayBean
     */
    //12
    public SmTbAccountPayBean loadByPrimaryKey(Integer index) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM sm_tb_account_pay WHERE sm_tb_account_pay.index=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Manager.setInteger(ps, 1, index);
            SmTbAccountPayBean pReturn[] = loadByPreparedStatement(ps);
            if (pReturn.length < 1)
                return null;
            else
                return pReturn[0];
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @return the number of deleted rows
     */
    //60
    public int deleteByPrimaryKey(Integer index) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("DELETE from sm_tb_account_pay WHERE sm_tb_account_pay.index=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Manager.setInteger(ps, 1, index);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }


    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from sm_tb_account_pay.
     *
     * @return an array of SmTbAccountPayManager pObject
     */
    //38
    public SmTbAccountPayBean[] loadAll() throws SQLException
    {
        return loadAll(1, -1);
    }


    /**
     * Loads the given number of rows from sm_tb_account_pay, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of SmTbAccountPayManager pObject
     */
    //38.5
    public SmTbAccountPayBean[] loadAll(int startRow, int numRows) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM sm_tb_account_pay",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            return loadByPreparedStatement(ps, null, startRow, numRows);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of SmTbAccountPayBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting SmTbAccountPayBean table
     */
    //49
    public SmTbAccountPayBean[] loadByWhere(String where) throws SQLException
    {
        return loadByWhere(where, null);
    }

    /**
     * Retrieves an array of SmTbAccountPayBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param fieldList table of the field's associated constants
     * @return the resulting SmTbAccountPayBean table
     */
    //51
    public SmTbAccountPayBean[] loadByWhere(String where, int[] fieldList) throws SQLException
    {
        return loadByWhere(where, null, 1, -1);
    }

    /**
     * Retrieves an array of SmTbAccountPayBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting SmTbAccountPayBean table
     */
    //51.5
    public SmTbAccountPayBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws SQLException
    {
        String sql = null;
        if(fieldList == null)
            sql = "select " + ALL_FIELDS + " from sm_tb_account_pay " + where;
        else
        {
            StringBuffer buff = new StringBuffer(128);
            buff.append("select ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0)
                    buff.append(",");
                buff.append(FIELD_NAMES[fieldList[i]]);
            }
            buff.append(" from sm_tb_account_pay ");
            buff.append(where);
            sql = buff.toString();
            buff = null;
        }
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        java.util.ArrayList v = null;
        try
        {
            c = getConnection();
            pStatement = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs =  pStatement.executeQuery(sql);
            v = new java.util.ArrayList();
            int count = 0;
            if (rs.absolute(startRow) && numRows!=0) {
                do
                {
                    if(fieldList == null)
                        v.add(decodeRow(rs));
                    else
                        v.add(decodeRow(rs, fieldList));
                    count++;
                } while ( (count<numRows||numRows<0) && rs.next() );
            }

            return (SmTbAccountPayBean[])v.toArray(new SmTbAccountPayBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); }
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
    }


    /**
     * Deletes all rows from sm_tb_account_pay table.
     * @return the number of deleted rows.
     */
    public int deleteAll() throws SQLException
    {
        return deleteByWhere("");
    }


    /**
     * Deletes rows from the sm_tb_account_pay table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     */
    public int deleteByWhere(String where) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = getConnection();
            String delByWhereSQL = "DELETE FROM sm_tb_account_pay " + where;
            ps = c.prepareStatement(delByWhereSQL);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // SAVE
    ///////////////////////////////////////////////////////////////////////
    /**
     * Saves the SmTbAccountPayBean pObject into the database.
     *
     * @param pObject the SmTbAccountPayBean pObject to be saved
     */
    //100
    public SmTbAccountPayBean save(SmTbAccountPayBean pObject) throws SQLException
    {
        if (!pObject.isModified()) {
            return pObject; // should not we log something ?
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;

        try
        {
            c = getConnection();
            if (pObject.isNew())
            { // SAVE
                beforeInsert(pObject); // listener callback
                int _dirtyCount = 0;
                _sql = new StringBuffer("INSERT into sm_tb_account_pay (");

                if (pObject.isIndexModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("index");
                    _dirtyCount++;
                }

                if (pObject.isUserIdModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("user_id");
                    _dirtyCount++;
                }

                if (pObject.isPayedModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("payed");
                    _dirtyCount++;
                }

                if (pObject.isCreateDateModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("create_date");
                    _dirtyCount++;
                }

                if (pObject.isCreateUserModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("create_user");
                    _dirtyCount++;
                }

                if (pObject.isModifyDateModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("modify_date");
                    _dirtyCount++;
                }

                if (pObject.isModifyUserModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("modify_user");
                    _dirtyCount++;
                }

                _sql.append(") values (");
                if(_dirtyCount > 0) {
                    _sql.append("?");
                    for(int i = 1; i < _dirtyCount; i++) {
                        _sql.append(",?");
                    }
                }
                _sql.append(")");

                ps = c.prepareStatement(_sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                _dirtyCount = 0;

                if (pObject.isIndexModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getIndex());
                }

                if (pObject.isUserIdModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
                }

                if (pObject.isPayedModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getPayed());
                }

                if (pObject.isCreateDateModified()) {
                    if (pObject.getCreateDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getCreateDate().getTime()));
                }

                if (pObject.isCreateUserModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getCreateUser());
                }

                if (pObject.isModifyDateModified()) {
                    if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getModifyDate().getTime()));
                }

                if (pObject.isModifyUserModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getModifyUser());
                }

                ps.executeUpdate();

                if (!pObject.isIndexModified())
                {
                    PreparedStatement ps2 = null;
                    ResultSet rs = null;
                    try {
                        ps2 = c.prepareStatement("SELECT last_insert_id()");
                        rs = ps2.executeQuery();
                        if(rs.next()) {
                            pObject.setIndex(Manager.getInteger(rs, 1));
                        } else {
                            getManager().log("ATTENTION: Could not retrieve generated key!");
                        }
                    } finally {
                        getManager().close(ps2, rs);
                    }
                }

                pObject.isNew(false);
                pObject.resetIsModified();
                afterInsert(pObject); // listener callback
            }
            else
            { // UPDATE
                beforeUpdate(pObject); // listener callback
                _sql = new StringBuffer("UPDATE sm_tb_account_pay SET ");
                boolean useComma=false;

                if (pObject.isIndexModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("index").append("=?");
                }

                if (pObject.isUserIdModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("user_id").append("=?");
                }

                if (pObject.isPayedModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("payed").append("=?");
                }

                if (pObject.isCreateDateModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("create_date").append("=?");
                }

                if (pObject.isCreateUserModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("create_user").append("=?");
                }

                if (pObject.isModifyDateModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("modify_date").append("=?");
                }

                if (pObject.isModifyUserModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("modify_user").append("=?");
                }
                _sql.append(" WHERE ");
                _sql.append("sm_tb_account_pay.index=?");
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                int _dirtyCount = 0;

                if (pObject.isIndexModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getIndex());
                }

                if (pObject.isUserIdModified()) {
                      Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
                }

                if (pObject.isPayedModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getPayed());
                }

                if (pObject.isCreateDateModified()) {
                      if (pObject.getCreateDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getCreateDate().getTime()));
                }

                if (pObject.isCreateUserModified()) {
                      Manager.setLong(ps, ++_dirtyCount, pObject.getCreateUser());
                }

                if (pObject.isModifyDateModified()) {
                      if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getModifyDate().getTime()));
                }

                if (pObject.isModifyUserModified()) {
                      Manager.setLong(ps, ++_dirtyCount, pObject.getModifyUser());
                }

                if (_dirtyCount == 0) {
                     return pObject;
                }

                Manager.setInteger(ps, ++_dirtyCount, pObject.getIndex());
                ps.executeUpdate();
                pObject.resetIsModified();
                afterUpdate(pObject); // listener callback
            }

            return pObject;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    /**
     * Saves an array of SmTbAccountPayBean pObjects into the database.
     *
     * @param pObjects the SmTbAccountPayBean pObject table to be saved
     * @return the saved SmTbAccountPayBean array.
     */
    //65
    public SmTbAccountPayBean[] save(SmTbAccountPayBean[] pObjects) throws SQLException
    {
        for (int iIndex = 0; iIndex < pObjects.length; iIndex ++){
            save(pObjects[iIndex]);
        }
        return pObjects;
    }



    ///////////////////////////////////////////////////////////////////////
    // USING TEMPLATE
    ///////////////////////////////////////////////////////////////////////
    /**
     * Loads a unique SmTbAccountPayBean pObject from a template one giving a c
     *
     * @param pObject the SmTbAccountPayBean pObject to look for
     * @return the pObject matching the template
     */
    //85
    public SmTbAccountPayBean loadUniqueUsingTemplate(SmTbAccountPayBean pObject) throws SQLException
    {
         SmTbAccountPayBean[] pReturn = loadUsingTemplate(pObject);
         if (pReturn.length == 0)
             return null;
         if (pReturn.length > 1)
             throw new SQLException("More than one element !!");
         return pReturn[0];
     }

    /**
     * Loads an array of SmTbAccountPayBean from a template one.
     *
     * @param pObject the SmTbAccountPayBean template to look for
     * @return all the SmTbAccountPayBean matching the template
     */
    //88
    public SmTbAccountPayBean[] loadUsingTemplate(SmTbAccountPayBean pObject) throws SQLException
    {
        return loadUsingTemplate(pObject, 1, -1);
    }
    /**
     * Loads an array of SmTbAccountPayBean from a template one, given the start row and number of rows.
     *
     * @param pObject the SmTbAccountPayBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the SmTbAccountPayBean matching the template
     */
    //88.5
    public SmTbAccountPayBean[] loadUsingTemplate(SmTbAccountPayBean pObject, int startRow, int numRows) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer where = new StringBuffer("");
        StringBuffer _sql = new StringBuffer("SELECT " + ALL_FIELDS + " from sm_tb_account_pay WHERE ");
        StringBuffer _sqlWhere = new StringBuffer("");
        try
        {
            int _dirtyCount = 0;

             if (pObject.isIndexModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("index= ?");
             }

             if (pObject.isUserIdModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("user_id= ?");
             }

             if (pObject.isPayedModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("payed= ?");
             }

             if (pObject.isCreateDateModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("create_date= ?");
             }

             if (pObject.isCreateUserModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("create_user= ?");
             }

             if (pObject.isModifyDateModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("modify_date= ?");
             }

             if (pObject.isModifyUserModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("modify_user= ?");
             }

             if (_dirtyCount == 0) {
                 throw new SQLException ("The pObject to look for is invalid : not initialized !");
             }
             _sql.append(_sqlWhere);
             c = getConnection();
             ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
             _dirtyCount = 0;

             if (pObject.isIndexModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getIndex());
             }

             if (pObject.isUserIdModified()) {
                 Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
             }

             if (pObject.isPayedModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getPayed());
             }

             if (pObject.isCreateDateModified()) {
                 if (pObject.getCreateDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getCreateDate().getTime()));
             }

             if (pObject.isCreateUserModified()) {
                 Manager.setLong(ps, ++_dirtyCount, pObject.getCreateUser());
             }

             if (pObject.isModifyDateModified()) {
                 if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getModifyDate().getTime()));
             }

             if (pObject.isModifyUserModified()) {
                 Manager.setLong(ps, ++_dirtyCount, pObject.getModifyUser());
             }

             ps.executeQuery();
             return loadByPreparedStatement(ps, null, startRow, numRows);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }
    /**
     * Deletes rows using a SmTbAccountPayBean template.
     *
     * @param pObject the SmTbAccountPayBean object(s) to be deleted
     * @return the number of deleted objects
     */
    //63
    public int deleteUsingTemplate(SmTbAccountPayBean pObject) throws SQLException
    {
        if (pObject.isIndexInitialized())
            return deleteByPrimaryKey(pObject.getIndex());

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            sql = new StringBuffer("DELETE FROM sm_tb_account_pay WHERE ");
            int _dirtyAnd = 0;
            if (pObject.isIndexInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("index").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isUserIdInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("user_id").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isPayedInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("payed").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isCreateDateInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("create_date").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isCreateUserInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("create_user").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isModifyDateInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("modify_date").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isModifyUserInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("modify_user").append("=?");
                _dirtyAnd ++;
            }

            c = getConnection();
            ps = c.prepareStatement(sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            int _dirtyCount = 0;

            if (pObject.isIndexInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getIndex());
            }

            if (pObject.isUserIdInitialized()) {
                Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
            }

            if (pObject.isPayedInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getPayed());
            }

            if (pObject.isCreateDateInitialized()) {
                if (pObject.getCreateDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getCreateDate().getTime()));
            }

            if (pObject.isCreateUserInitialized()) {
                Manager.setLong(ps, ++_dirtyCount, pObject.getCreateUser());
            }

            if (pObject.isModifyDateInitialized()) {
                if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getModifyDate().getTime()));
            }

            if (pObject.isModifyUserInitialized()) {
                Manager.setLong(ps, ++_dirtyCount, pObject.getModifyUser());
            }

            int _rows = ps.executeUpdate();
            return _rows;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // COUNT
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the number of rows of the table sm_tb_account_pay.
     *
     * @return the number of rows returned
     */
    //78
    public int countAll() throws SQLException
    {
        return countWhere("");
    }



    /**
     * Retrieves the number of rows of the table sm_tb_account_pay with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     */
    public int countWhere(String where) throws SQLException
    {
        String sql = "select count(*) as MCOUNT from sm_tb_account_pay " + where;
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = getConnection();
            pStatement = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs =  pStatement.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
       throw new SQLException("Error in countWhere");
    }

    /**
     * Retrieves the number of rows of the table sm_tb_account_pay with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     */
    //82
    int countByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next())
                iReturn = rs.getInt("MCOUNT");
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(rs);
        }
       throw new SQLException("Error in countByPreparedStatement");
    }

    /**
     * Looks for the number of elements of a specific SmTbAccountPayBean pObject given a c
     *
     * @param pObject the SmTbAccountPayBean pObject to look for
     * @return the number of rows returned
     */
    //83
    public int countUsingTemplate(SmTbAccountPayBean pObject) throws SQLException
    {
        StringBuffer where = new StringBuffer("");
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;
        StringBuffer _sqlWhere = null;

        try
        {
                _sql = new StringBuffer("SELECT count(*) as MCOUNT  from sm_tb_account_pay WHERE ");
                _sqlWhere = new StringBuffer("");
                int _dirtyCount = 0;

                if (pObject.isIndexModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("index= ?");
                }

                if (pObject.isUserIdModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("user_id= ?");
                }

                if (pObject.isPayedModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("payed= ?");
                }

                if (pObject.isCreateDateModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("create_date= ?");
                }

                if (pObject.isCreateUserModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("create_user= ?");
                }

                if (pObject.isModifyDateModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("modify_date= ?");
                }

                if (pObject.isModifyUserModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("modify_user= ?");
                }

                if (_dirtyCount == 0)
                   throw new SQLException ("The pObject to look is unvalid : not initialized !");

                _sql.append(_sqlWhere);
                c = getConnection();
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                _dirtyCount = 0;

                if (pObject.isIndexModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getIndex());
                }

                if (pObject.isUserIdModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getUserId());
                }

                if (pObject.isPayedModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getPayed());
                }

                if (pObject.isCreateDateModified()) {
                    if (pObject.getCreateDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getCreateDate().getTime()));
                }

                if (pObject.isCreateUserModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getCreateUser());
                }

                if (pObject.isModifyDateModified()) {
                    if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.TIMESTAMP); else ps.setTimestamp(++_dirtyCount, new java.sql.Timestamp(pObject.getModifyDate().getTime()));
                }

                if (pObject.isModifyUserModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getModifyUser());
                }

                return countByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // DECODE RESULT SET
    ///////////////////////////////////////////////////////////////////////
    /**
     * Transforms a ResultSet iterating on the sm_tb_account_pay on a SmTbAccountPayBean pObject.
     *
     * @param rs the ResultSet to be transformed
     * @return pObject resulting SmTbAccountPayBean pObject
     */
    //72
    public SmTbAccountPayBean decodeRow(ResultSet rs) throws SQLException
    {
        SmTbAccountPayBean pObject = createSmTbAccountPayBean();
        pObject.setIndex(Manager.getInteger(rs, 1));
        pObject.setUserId(Manager.getLong(rs, 2));
        pObject.setPayed(Manager.getInteger(rs, 3));
        pObject.setCreateDate(rs.getTimestamp(4));
        pObject.setCreateUser(Manager.getLong(rs, 5));
        pObject.setModifyDate(rs.getTimestamp(6));
        pObject.setModifyUser(Manager.getLong(rs, 7));

        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    /**
     * Transforms a ResultSet iterating on the sm_tb_account_pay table on a SmTbAccountPayBean pObject according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return pObject resulting SmTbAccountPayBean pObject
     */
    //73
    public SmTbAccountPayBean decodeRow(ResultSet rs, int[] fieldList) throws SQLException
    {
        SmTbAccountPayBean pObject = createSmTbAccountPayBean();
        int pos = 0;
        for(int i = 0; i < fieldList.length; i++)
        {
            switch(fieldList[i]) {
                case ID_INDEX:
                    ++pos;
                    pObject.setIndex(Manager.getInteger(rs, pos));
                    break;
                case ID_USER_ID:
                    ++pos;
                    pObject.setUserId(Manager.getLong(rs, pos));
                    break;
                case ID_PAYED:
                    ++pos;
                    pObject.setPayed(Manager.getInteger(rs, pos));
                    break;
                case ID_CREATE_DATE:
                    ++pos;
                    pObject.setCreateDate(rs.getTimestamp(pos));
                    break;
                case ID_CREATE_USER:
                    ++pos;
                    pObject.setCreateUser(Manager.getLong(rs, pos));
                    break;
                case ID_MODIFY_DATE:
                    ++pos;
                    pObject.setModifyDate(rs.getTimestamp(pos));
                    break;
                case ID_MODIFY_USER:
                    ++pos;
                    pObject.setModifyUser(Manager.getLong(rs, pos));
                    break;
            }
        }
        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of SmTbAccountPayBean
     */
    //41
    public SmTbAccountPayBean[] loadByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        return loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of SmTbAccountPayBean
     */
    public SmTbAccountPayBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws SQLException
    {
        return loadByPreparedStatement(ps, fieldList, 1, -1);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of SmTbAccountPayBean
     */
    //41.5
    public SmTbAccountPayBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws SQLException
    {
        ResultSet rs =  null;
        java.util.ArrayList v =  null;
        try
        {
            rs =  ps.executeQuery();
            v = new java.util.ArrayList();
            int count = 0;
            if (rs.absolute(startRow) && numRows!=0) {
                do
                {
                    if(fieldList == null)
                        v.add(decodeRow(rs));
                    else
                        v.add(decodeRow(rs, fieldList));
                    count++;
                } while ( (count<numRows||numRows<0) && rs.next() );
            }
            return (SmTbAccountPayBean[])v.toArray(new SmTbAccountPayBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    ///////////////////////////////////////////////////////////////////////
    // LISTENER
    ///////////////////////////////////////////////////////////////////////
    private SmTbAccountPayListener listener = null;

    /**
     * Registers a unique SmTbAccountPayListener listener.
     */
    //66.5
    public void registerListener(SmTbAccountPayListener listener) {
        this.listener = listener;
    }

    /**
     * Before the save of the SmTbAccountPayBean pObject.
     *
     * @param pObject the SmTbAccountPayBean pObject to be saved
     */
    //67
    void beforeInsert(SmTbAccountPayBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeInsert(pObject);
    }

    /**
     * After the save of the SmTbAccountPayBean pObject.
     *
     * @param pObject the SmTbAccountPayBean pObject to be saved
     */
    //68
    void afterInsert(SmTbAccountPayBean pObject) throws SQLException {
        if (listener != null)
            listener.afterInsert(pObject);
    }

    /**
     * Before the update of the SmTbAccountPayBean pObject.
     *
     * @param pObject the SmTbAccountPayBean pObject to be updated
     */
    //69
    void beforeUpdate(SmTbAccountPayBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeUpdate(pObject);
    }

    /**
     * After the update of the SmTbAccountPayBean pObject.
     *
     * @param pObject the SmTbAccountPayBean pObject to be updated
     */
    //70
    void afterUpdate(SmTbAccountPayBean pObject) throws SQLException {
        if (listener != null)
            listener.afterUpdate(pObject);
    }

    ///////////////////////////////////////////////////////////////////////
    // UTILS
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //2
    Manager getManager() {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    void freeConnection(Connection c) {
        getManager().releaseConnection(c); // back to pool
    }
    /**
     * Gets the connection.
     */
    Connection getConnection() throws SQLException {
        return getManager().getConnection();
    }

// class+ 

// class- 
}
