// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of sm_tb_sale_record table changes.
 */
public interface SmTbSaleRecordListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a SmTbSaleRecordBean record into the database.
     *
     * @param pObject the SmTbSaleRecordBean that is about to be inserted
     */
    public void beforeInsert(SmTbSaleRecordBean pObject) throws SQLException;


    /**
     * Invoked just after a SmTbSaleRecordBean record is inserted in the database.
     *
     * @param pObject the SmTbSaleRecordBean that was just inserted
     */
    public void afterInsert(SmTbSaleRecordBean pObject) throws SQLException;


    /**
     * Invoked just before updating a SmTbSaleRecordBean record in the database.
     *
     * @param pObject the SmTbSaleRecordBean that is about to be updated
     */
    public void beforeUpdate(SmTbSaleRecordBean pObject) throws SQLException;


    /**
     * Invoked just after updating a SmTbSaleRecordBean record in the database.
     *
     * @param pObject the SmTbSaleRecordBean that was just updated
     */
    public void afterUpdate(SmTbSaleRecordBean pObject) throws SQLException;


// class+ 

// class- 
}
