// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the SmTbSaleItemLogBean objects.
 */
public class SmTbSaleItemLogComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for SmTbSaleItemLogComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new SmTbSaleItemLogComparator(SmTbSaleItemLogManager.IDX, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>SmTbSaleItemLogManager.ID_IDX
     *   <li>SmTbSaleItemLogManager.ID_ITEM_SEQ
     *   <li>SmTbSaleItemLogManager.ID_ITEM_LOG
     *   <li>SmTbSaleItemLogManager.ID_CREATE_USER
     *   <li>SmTbSaleItemLogManager.ID_CREATE_DATE
     * </ul>
     */
    public SmTbSaleItemLogComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for SmTbSaleItemLogComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new SmTbSaleItemLogComparator(SmTbSaleItemLogManager.IDX, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>SmTbSaleItemLogManager.ID_IDX
     *   <li>SmTbSaleItemLogManager.ID_ITEM_SEQ
     *   <li>SmTbSaleItemLogManager.ID_ITEM_LOG
     *   <li>SmTbSaleItemLogManager.ID_CREATE_USER
     *   <li>SmTbSaleItemLogManager.ID_CREATE_DATE
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public SmTbSaleItemLogComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        SmTbSaleItemLogBean b1 = (SmTbSaleItemLogBean)pObj1;
        SmTbSaleItemLogBean b2 = (SmTbSaleItemLogBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case SmTbSaleItemLogManager.ID_IDX:
                if (b1.getIdx() == null && b2.getIdx() != null) {
                    iReturn = -1;
                } else if (b1.getIdx() == null && b2.getIdx() == null) {
                    iReturn = 0;
                } else if (b1.getIdx() != null && b2.getIdx() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getIdx().compareTo(b2.getIdx());
                }
                break;
            case SmTbSaleItemLogManager.ID_ITEM_SEQ:
                if (b1.getItemSeq() == null && b2.getItemSeq() != null) {
                    iReturn = -1;
                } else if (b1.getItemSeq() == null && b2.getItemSeq() == null) {
                    iReturn = 0;
                } else if (b1.getItemSeq() != null && b2.getItemSeq() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getItemSeq().compareTo(b2.getItemSeq());
                }
                break;
            case SmTbSaleItemLogManager.ID_ITEM_LOG:
                if (b1.getItemLog() == null && b2.getItemLog() != null) {
                    iReturn = -1;
                } else if (b1.getItemLog() == null && b2.getItemLog() == null) {
                    iReturn = 0;
                } else if (b1.getItemLog() != null && b2.getItemLog() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getItemLog().compareTo(b2.getItemLog());
                }
                break;
            case SmTbSaleItemLogManager.ID_CREATE_USER:
                if (b1.getCreateUser() == null && b2.getCreateUser() != null) {
                    iReturn = -1;
                } else if (b1.getCreateUser() == null && b2.getCreateUser() == null) {
                    iReturn = 0;
                } else if (b1.getCreateUser() != null && b2.getCreateUser() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getCreateUser().compareTo(b2.getCreateUser());
                }
                break;
            case SmTbSaleItemLogManager.ID_CREATE_DATE:
                if (b1.getCreateDate() == null && b2.getCreateDate() != null) {
                    iReturn = -1;
                } else if (b1.getCreateDate() == null && b2.getCreateDate() == null) {
                    iReturn = 0;
                } else if (b1.getCreateDate() != null && b2.getCreateDate() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getCreateDate().compareTo(b2.getCreateDate());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
