// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of sm_tb_vip_account table changes.
 */
public interface SmTbVipAccountListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a SmTbVipAccountBean record into the database.
     *
     * @param pObject the SmTbVipAccountBean that is about to be inserted
     */
    public void beforeInsert(SmTbVipAccountBean pObject) throws SQLException;


    /**
     * Invoked just after a SmTbVipAccountBean record is inserted in the database.
     *
     * @param pObject the SmTbVipAccountBean that was just inserted
     */
    public void afterInsert(SmTbVipAccountBean pObject) throws SQLException;


    /**
     * Invoked just before updating a SmTbVipAccountBean record in the database.
     *
     * @param pObject the SmTbVipAccountBean that is about to be updated
     */
    public void beforeUpdate(SmTbVipAccountBean pObject) throws SQLException;


    /**
     * Invoked just after updating a SmTbVipAccountBean record in the database.
     *
     * @param pObject the SmTbVipAccountBean that was just updated
     */
    public void afterUpdate(SmTbVipAccountBean pObject) throws SQLException;


// class+ 

// class- 
}
