// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of sm_vw_sale_item table changes.
 */
public interface SmVwSaleItemListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a SmVwSaleItemBean record into the database.
     *
     * @param pObject the SmVwSaleItemBean that is about to be inserted
     */
    public void beforeInsert(SmVwSaleItemBean pObject) throws SQLException;


    /**
     * Invoked just after a SmVwSaleItemBean record is inserted in the database.
     *
     * @param pObject the SmVwSaleItemBean that was just inserted
     */
    public void afterInsert(SmVwSaleItemBean pObject) throws SQLException;


    /**
     * Invoked just before updating a SmVwSaleItemBean record in the database.
     *
     * @param pObject the SmVwSaleItemBean that is about to be updated
     */
    public void beforeUpdate(SmVwSaleItemBean pObject) throws SQLException;


    /**
     * Invoked just after updating a SmVwSaleItemBean record in the database.
     *
     * @param pObject the SmVwSaleItemBean that was just updated
     */
    public void afterUpdate(SmVwSaleItemBean pObject) throws SQLException;


// class+ 

// class- 
}
