// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.shenming.sms.dc.sql2java;

import java.sql.*;
// imports+ 

// imports- 

/**
 * Handles database calls for the sys_tb_properties table.
 */
public class SysTbPropertiesManager
// extends+ 

// extends- 
{

    /**
     * Column idx of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_IDX = 0;
    public static final int TYPE_IDX = Types.INTEGER;
    public static final String NAME_IDX = "idx";

    /**
     * Column key_name of type Types.VARCHAR mapped to String.
     */
    public static final int ID_KEY_NAME = 1;
    public static final int TYPE_KEY_NAME = Types.VARCHAR;
    public static final String NAME_KEY_NAME = "key_name";

    /**
     * Column key_value of type Types.VARCHAR mapped to String.
     */
    public static final int ID_KEY_VALUE = 2;
    public static final int TYPE_KEY_VALUE = Types.VARCHAR;
    public static final String NAME_KEY_VALUE = "key_value";

    /**
     * Column key_group of type Types.VARCHAR mapped to String.
     */
    public static final int ID_KEY_GROUP = 3;
    public static final int TYPE_KEY_GROUP = Types.VARCHAR;
    public static final String NAME_KEY_GROUP = "key_group";

    /**
     * Column description of type Types.VARCHAR mapped to String.
     */
    public static final int ID_DESCRIPTION = 4;
    public static final int TYPE_DESCRIPTION = Types.VARCHAR;
    public static final String NAME_DESCRIPTION = "description";

    /**
     * Column modify_date of type Types.DATE mapped to java.util.Date.
     */
    public static final int ID_MODIFY_DATE = 5;
    public static final int TYPE_MODIFY_DATE = Types.DATE;
    public static final String NAME_MODIFY_DATE = "modify_date";


    private static final String TABLE_NAME = "sys_tb_properties";

    /**
     * Create an array of type string containing all the fields of the sys_tb_properties table.
     */
    private static final String[] FIELD_NAMES =
    {
        "sys_tb_properties.idx"
        ,"sys_tb_properties.key_name"
        ,"sys_tb_properties.key_value"
        ,"sys_tb_properties.key_group"
        ,"sys_tb_properties.description"
        ,"sys_tb_properties.modify_date"
    };

    /**
     * Field that contains the comma separated fields of the sys_tb_properties table.
     */
    private static final String ALL_FIELDS = "sys_tb_properties.idx"
                            + ",sys_tb_properties.key_name"
                            + ",sys_tb_properties.key_value"
                            + ",sys_tb_properties.key_group"
                            + ",sys_tb_properties.description"
                            + ",sys_tb_properties.modify_date";

    private static SysTbPropertiesManager singleton = new SysTbPropertiesManager();

    /**
     * Get the SysTbPropertiesManager singleton.
     *
     * @return SysTbPropertiesManager
     */
    synchronized public static SysTbPropertiesManager getInstance()
    {
        return singleton;
    }

    /**
     * Sets your own SysTbPropertiesManager instance.
     <br>
     * This is optional, by default we provide it for you.
     */
    synchronized public static void setInstance(SysTbPropertiesManager instance)
    {
        singleton = instance;
    }


    /**
     * Creates a new SysTbPropertiesBean instance.
     *
     * @return the new SysTbPropertiesBean
     */
    public SysTbPropertiesBean createSysTbPropertiesBean()
    {
        return new SysTbPropertiesBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a SysTbPropertiesBean from the sys_tb_properties using its key fields.
     *
     * @return a unique SysTbPropertiesBean
     */
    //12
    public SysTbPropertiesBean loadByPrimaryKey(Integer idx) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM sys_tb_properties WHERE sys_tb_properties.idx=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Manager.setInteger(ps, 1, idx);
            SysTbPropertiesBean pReturn[] = loadByPreparedStatement(ps);
            if (pReturn.length < 1)
                return null;
            else
                return pReturn[0];
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @return the number of deleted rows
     */
    //60
    public int deleteByPrimaryKey(Integer idx) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("DELETE from sys_tb_properties WHERE sys_tb_properties.idx=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Manager.setInteger(ps, 1, idx);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }


    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from sys_tb_properties.
     *
     * @return an array of SysTbPropertiesManager pObject
     */
    //38
    public SysTbPropertiesBean[] loadAll() throws SQLException
    {
        return loadAll(1, -1);
    }


    /**
     * Loads the given number of rows from sys_tb_properties, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of SysTbPropertiesManager pObject
     */
    //38.5
    public SysTbPropertiesBean[] loadAll(int startRow, int numRows) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM sys_tb_properties",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            return loadByPreparedStatement(ps, null, startRow, numRows);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of SysTbPropertiesBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting SysTbPropertiesBean table
     */
    //49
    public SysTbPropertiesBean[] loadByWhere(String where) throws SQLException
    {
        return loadByWhere(where, null);
    }

    /**
     * Retrieves an array of SysTbPropertiesBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param fieldList table of the field's associated constants
     * @return the resulting SysTbPropertiesBean table
     */
    //51
    public SysTbPropertiesBean[] loadByWhere(String where, int[] fieldList) throws SQLException
    {
        return loadByWhere(where, null, 1, -1);
    }

    /**
     * Retrieves an array of SysTbPropertiesBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting SysTbPropertiesBean table
     */
    //51.5
    public SysTbPropertiesBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws SQLException
    {
        String sql = null;
        if(fieldList == null)
            sql = "select " + ALL_FIELDS + " from sys_tb_properties " + where;
        else
        {
            StringBuffer buff = new StringBuffer(128);
            buff.append("select ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0)
                    buff.append(",");
                buff.append(FIELD_NAMES[fieldList[i]]);
            }
            buff.append(" from sys_tb_properties ");
            buff.append(where);
            sql = buff.toString();
            buff = null;
        }
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        java.util.ArrayList v = null;
        try
        {
            c = getConnection();
            pStatement = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs =  pStatement.executeQuery(sql);
            v = new java.util.ArrayList();
            int count = 0;
            if (rs.absolute(startRow) && numRows!=0) {
                do
                {
                    if(fieldList == null)
                        v.add(decodeRow(rs));
                    else
                        v.add(decodeRow(rs, fieldList));
                    count++;
                } while ( (count<numRows||numRows<0) && rs.next() );
            }

            return (SysTbPropertiesBean[])v.toArray(new SysTbPropertiesBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); }
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
    }


    /**
     * Deletes all rows from sys_tb_properties table.
     * @return the number of deleted rows.
     */
    public int deleteAll() throws SQLException
    {
        return deleteByWhere("");
    }


    /**
     * Deletes rows from the sys_tb_properties table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     */
    public int deleteByWhere(String where) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = getConnection();
            String delByWhereSQL = "DELETE FROM sys_tb_properties " + where;
            ps = c.prepareStatement(delByWhereSQL);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // SAVE
    ///////////////////////////////////////////////////////////////////////
    /**
     * Saves the SysTbPropertiesBean pObject into the database.
     *
     * @param pObject the SysTbPropertiesBean pObject to be saved
     */
    //100
    public SysTbPropertiesBean save(SysTbPropertiesBean pObject) throws SQLException
    {
        if (!pObject.isModified()) {
            return pObject; // should not we log something ?
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;

        try
        {
            c = getConnection();
            if (pObject.isNew())
            { // SAVE
                beforeInsert(pObject); // listener callback
                int _dirtyCount = 0;
                _sql = new StringBuffer("INSERT into sys_tb_properties (");

                if (pObject.isIdxModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("idx");
                    _dirtyCount++;
                }

                if (pObject.isKeyNameModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("key_name");
                    _dirtyCount++;
                }

                if (pObject.isKeyValueModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("key_value");
                    _dirtyCount++;
                }

                if (pObject.isKeyGroupModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("key_group");
                    _dirtyCount++;
                }

                if (pObject.isDescriptionModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("description");
                    _dirtyCount++;
                }

                if (pObject.isModifyDateModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("modify_date");
                    _dirtyCount++;
                }

                _sql.append(") values (");
                if(_dirtyCount > 0) {
                    _sql.append("?");
                    for(int i = 1; i < _dirtyCount; i++) {
                        _sql.append(",?");
                    }
                }
                _sql.append(")");

                ps = c.prepareStatement(_sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                _dirtyCount = 0;

                if (pObject.isIdxModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getIdx());
                }

                if (pObject.isKeyNameModified()) {
                    ps.setString(++_dirtyCount, pObject.getKeyName());
                }

                if (pObject.isKeyValueModified()) {
                    ps.setString(++_dirtyCount, pObject.getKeyValue());
                }

                if (pObject.isKeyGroupModified()) {
                    ps.setString(++_dirtyCount, pObject.getKeyGroup());
                }

                if (pObject.isDescriptionModified()) {
                    ps.setString(++_dirtyCount, pObject.getDescription());
                }

                if (pObject.isModifyDateModified()) {
                    if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.DATE); else ps.setDate(++_dirtyCount, new java.sql.Date(pObject.getModifyDate().getTime()));
                }

                ps.executeUpdate();

                if (!pObject.isIdxModified())
                {
                    PreparedStatement ps2 = null;
                    ResultSet rs = null;
                    try {
                        ps2 = c.prepareStatement("SELECT last_insert_id()");
                        rs = ps2.executeQuery();
                        if(rs.next()) {
                            pObject.setIdx(Manager.getInteger(rs, 1));
                        } else {
                            getManager().log("ATTENTION: Could not retrieve generated key!");
                        }
                    } finally {
                        getManager().close(ps2, rs);
                    }
                }

                pObject.isNew(false);
                pObject.resetIsModified();
                afterInsert(pObject); // listener callback
            }
            else
            { // UPDATE
                beforeUpdate(pObject); // listener callback
                _sql = new StringBuffer("UPDATE sys_tb_properties SET ");
                boolean useComma=false;

                if (pObject.isIdxModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("idx").append("=?");
                }

                if (pObject.isKeyNameModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("key_name").append("=?");
                }

                if (pObject.isKeyValueModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("key_value").append("=?");
                }

                if (pObject.isKeyGroupModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("key_group").append("=?");
                }

                if (pObject.isDescriptionModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("description").append("=?");
                }

                if (pObject.isModifyDateModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("modify_date").append("=?");
                }
                _sql.append(" WHERE ");
                _sql.append("sys_tb_properties.idx=?");
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                int _dirtyCount = 0;

                if (pObject.isIdxModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getIdx());
                }

                if (pObject.isKeyNameModified()) {
                      ps.setString(++_dirtyCount, pObject.getKeyName());
                }

                if (pObject.isKeyValueModified()) {
                      ps.setString(++_dirtyCount, pObject.getKeyValue());
                }

                if (pObject.isKeyGroupModified()) {
                      ps.setString(++_dirtyCount, pObject.getKeyGroup());
                }

                if (pObject.isDescriptionModified()) {
                      ps.setString(++_dirtyCount, pObject.getDescription());
                }

                if (pObject.isModifyDateModified()) {
                      if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.DATE); else ps.setDate(++_dirtyCount, new java.sql.Date(pObject.getModifyDate().getTime()));
                }

                if (_dirtyCount == 0) {
                     return pObject;
                }

                Manager.setInteger(ps, ++_dirtyCount, pObject.getIdx());
                ps.executeUpdate();
                pObject.resetIsModified();
                afterUpdate(pObject); // listener callback
            }

            return pObject;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    /**
     * Saves an array of SysTbPropertiesBean pObjects into the database.
     *
     * @param pObjects the SysTbPropertiesBean pObject table to be saved
     * @return the saved SysTbPropertiesBean array.
     */
    //65
    public SysTbPropertiesBean[] save(SysTbPropertiesBean[] pObjects) throws SQLException
    {
        for (int iIndex = 0; iIndex < pObjects.length; iIndex ++){
            save(pObjects[iIndex]);
        }
        return pObjects;
    }



    ///////////////////////////////////////////////////////////////////////
    // USING TEMPLATE
    ///////////////////////////////////////////////////////////////////////
    /**
     * Loads a unique SysTbPropertiesBean pObject from a template one giving a c
     *
     * @param pObject the SysTbPropertiesBean pObject to look for
     * @return the pObject matching the template
     */
    //85
    public SysTbPropertiesBean loadUniqueUsingTemplate(SysTbPropertiesBean pObject) throws SQLException
    {
         SysTbPropertiesBean[] pReturn = loadUsingTemplate(pObject);
         if (pReturn.length == 0)
             return null;
         if (pReturn.length > 1)
             throw new SQLException("More than one element !!");
         return pReturn[0];
     }

    /**
     * Loads an array of SysTbPropertiesBean from a template one.
     *
     * @param pObject the SysTbPropertiesBean template to look for
     * @return all the SysTbPropertiesBean matching the template
     */
    //88
    public SysTbPropertiesBean[] loadUsingTemplate(SysTbPropertiesBean pObject) throws SQLException
    {
        return loadUsingTemplate(pObject, 1, -1);
    }
    /**
     * Loads an array of SysTbPropertiesBean from a template one, given the start row and number of rows.
     *
     * @param pObject the SysTbPropertiesBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the SysTbPropertiesBean matching the template
     */
    //88.5
    public SysTbPropertiesBean[] loadUsingTemplate(SysTbPropertiesBean pObject, int startRow, int numRows) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer where = new StringBuffer("");
        StringBuffer _sql = new StringBuffer("SELECT " + ALL_FIELDS + " from sys_tb_properties WHERE ");
        StringBuffer _sqlWhere = new StringBuffer("");
        try
        {
            int _dirtyCount = 0;

             if (pObject.isIdxModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("idx= ?");
             }

             if (pObject.isKeyNameModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("key_name= ?");
             }

             if (pObject.isKeyValueModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("key_value= ?");
             }

             if (pObject.isKeyGroupModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("key_group= ?");
             }

             if (pObject.isDescriptionModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("description= ?");
             }

             if (pObject.isModifyDateModified()) {
                 _dirtyCount ++;
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("modify_date= ?");
             }

             if (_dirtyCount == 0) {
                 throw new SQLException ("The pObject to look for is invalid : not initialized !");
             }
             _sql.append(_sqlWhere);
             c = getConnection();
             ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
             _dirtyCount = 0;

             if (pObject.isIdxModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getIdx());
             }

             if (pObject.isKeyNameModified()) {
                 ps.setString(++_dirtyCount, pObject.getKeyName());
             }

             if (pObject.isKeyValueModified()) {
                 ps.setString(++_dirtyCount, pObject.getKeyValue());
             }

             if (pObject.isKeyGroupModified()) {
                 ps.setString(++_dirtyCount, pObject.getKeyGroup());
             }

             if (pObject.isDescriptionModified()) {
                 ps.setString(++_dirtyCount, pObject.getDescription());
             }

             if (pObject.isModifyDateModified()) {
                 if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.DATE); else ps.setDate(++_dirtyCount, new java.sql.Date(pObject.getModifyDate().getTime()));
             }

             ps.executeQuery();
             return loadByPreparedStatement(ps, null, startRow, numRows);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }
    /**
     * Deletes rows using a SysTbPropertiesBean template.
     *
     * @param pObject the SysTbPropertiesBean object(s) to be deleted
     * @return the number of deleted objects
     */
    //63
    public int deleteUsingTemplate(SysTbPropertiesBean pObject) throws SQLException
    {
        if (pObject.isIdxInitialized())
            return deleteByPrimaryKey(pObject.getIdx());

        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;

        try
        {
            sql = new StringBuffer("DELETE FROM sys_tb_properties WHERE ");
            int _dirtyAnd = 0;
            if (pObject.isIdxInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("idx").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isKeyNameInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("key_name").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isKeyValueInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("key_value").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isKeyGroupInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("key_group").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isDescriptionInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("description").append("=?");
                _dirtyAnd ++;
            }

            if (pObject.isModifyDateInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("modify_date").append("=?");
                _dirtyAnd ++;
            }

            c = getConnection();
            ps = c.prepareStatement(sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            int _dirtyCount = 0;

            if (pObject.isIdxInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getIdx());
            }

            if (pObject.isKeyNameInitialized()) {
                ps.setString(++_dirtyCount, pObject.getKeyName());
            }

            if (pObject.isKeyValueInitialized()) {
                ps.setString(++_dirtyCount, pObject.getKeyValue());
            }

            if (pObject.isKeyGroupInitialized()) {
                ps.setString(++_dirtyCount, pObject.getKeyGroup());
            }

            if (pObject.isDescriptionInitialized()) {
                ps.setString(++_dirtyCount, pObject.getDescription());
            }

            if (pObject.isModifyDateInitialized()) {
                if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.DATE); else ps.setDate(++_dirtyCount, new java.sql.Date(pObject.getModifyDate().getTime()));
            }

            int _rows = ps.executeUpdate();
            return _rows;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // COUNT
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the number of rows of the table sys_tb_properties.
     *
     * @return the number of rows returned
     */
    //78
    public int countAll() throws SQLException
    {
        return countWhere("");
    }



    /**
     * Retrieves the number of rows of the table sys_tb_properties with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     */
    public int countWhere(String where) throws SQLException
    {
        String sql = "select count(*) as MCOUNT from sys_tb_properties " + where;
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = getConnection();
            pStatement = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs =  pStatement.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
       throw new SQLException("Error in countWhere");
    }

    /**
     * Retrieves the number of rows of the table sys_tb_properties with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     */
    //82
    int countByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next())
                iReturn = rs.getInt("MCOUNT");
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(rs);
        }
       throw new SQLException("Error in countByPreparedStatement");
    }

    /**
     * Looks for the number of elements of a specific SysTbPropertiesBean pObject given a c
     *
     * @param pObject the SysTbPropertiesBean pObject to look for
     * @return the number of rows returned
     */
    //83
    public int countUsingTemplate(SysTbPropertiesBean pObject) throws SQLException
    {
        StringBuffer where = new StringBuffer("");
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;
        StringBuffer _sqlWhere = null;

        try
        {
                _sql = new StringBuffer("SELECT count(*) as MCOUNT  from sys_tb_properties WHERE ");
                _sqlWhere = new StringBuffer("");
                int _dirtyCount = 0;

                if (pObject.isIdxModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("idx= ?");
                }

                if (pObject.isKeyNameModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("key_name= ?");
                }

                if (pObject.isKeyValueModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("key_value= ?");
                }

                if (pObject.isKeyGroupModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("key_group= ?");
                }

                if (pObject.isDescriptionModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("description= ?");
                }

                if (pObject.isModifyDateModified()) {
                    _dirtyCount++;
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("modify_date= ?");
                }

                if (_dirtyCount == 0)
                   throw new SQLException ("The pObject to look is unvalid : not initialized !");

                _sql.append(_sqlWhere);
                c = getConnection();
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

                _dirtyCount = 0;

                if (pObject.isIdxModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getIdx());
                }

                if (pObject.isKeyNameModified()) {
                    ps.setString(++_dirtyCount, pObject.getKeyName());
                }

                if (pObject.isKeyValueModified()) {
                    ps.setString(++_dirtyCount, pObject.getKeyValue());
                }

                if (pObject.isKeyGroupModified()) {
                    ps.setString(++_dirtyCount, pObject.getKeyGroup());
                }

                if (pObject.isDescriptionModified()) {
                    ps.setString(++_dirtyCount, pObject.getDescription());
                }

                if (pObject.isModifyDateModified()) {
                    if (pObject.getModifyDate() == null) ps.setNull(++_dirtyCount, Types.DATE); else ps.setDate(++_dirtyCount, new java.sql.Date(pObject.getModifyDate().getTime()));
                }

                return countByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // DECODE RESULT SET
    ///////////////////////////////////////////////////////////////////////
    /**
     * Transforms a ResultSet iterating on the sys_tb_properties on a SysTbPropertiesBean pObject.
     *
     * @param rs the ResultSet to be transformed
     * @return pObject resulting SysTbPropertiesBean pObject
     */
    //72
    public SysTbPropertiesBean decodeRow(ResultSet rs) throws SQLException
    {
        SysTbPropertiesBean pObject = createSysTbPropertiesBean();
        pObject.setIdx(Manager.getInteger(rs, 1));
        pObject.setKeyName(rs.getString(2));
        pObject.setKeyValue(rs.getString(3));
        pObject.setKeyGroup(rs.getString(4));
        pObject.setDescription(rs.getString(5));
        pObject.setModifyDate(rs.getDate(6));

        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    /**
     * Transforms a ResultSet iterating on the sys_tb_properties table on a SysTbPropertiesBean pObject according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return pObject resulting SysTbPropertiesBean pObject
     */
    //73
    public SysTbPropertiesBean decodeRow(ResultSet rs, int[] fieldList) throws SQLException
    {
        SysTbPropertiesBean pObject = createSysTbPropertiesBean();
        int pos = 0;
        for(int i = 0; i < fieldList.length; i++)
        {
            switch(fieldList[i]) {
                case ID_IDX:
                    ++pos;
                    pObject.setIdx(Manager.getInteger(rs, pos));
                    break;
                case ID_KEY_NAME:
                    ++pos;
                    pObject.setKeyName(rs.getString(pos));
                    break;
                case ID_KEY_VALUE:
                    ++pos;
                    pObject.setKeyValue(rs.getString(pos));
                    break;
                case ID_KEY_GROUP:
                    ++pos;
                    pObject.setKeyGroup(rs.getString(pos));
                    break;
                case ID_DESCRIPTION:
                    ++pos;
                    pObject.setDescription(rs.getString(pos));
                    break;
                case ID_MODIFY_DATE:
                    ++pos;
                    pObject.setModifyDate(rs.getDate(pos));
                    break;
            }
        }
        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of SysTbPropertiesBean
     */
    //41
    public SysTbPropertiesBean[] loadByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        return loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of SysTbPropertiesBean
     */
    public SysTbPropertiesBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws SQLException
    {
        return loadByPreparedStatement(ps, fieldList, 1, -1);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of SysTbPropertiesBean
     */
    //41.5
    public SysTbPropertiesBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws SQLException
    {
        ResultSet rs =  null;
        java.util.ArrayList v =  null;
        try
        {
            rs =  ps.executeQuery();
            v = new java.util.ArrayList();
            int count = 0;
            if (rs.absolute(startRow) && numRows!=0) {
                do
                {
                    if(fieldList == null)
                        v.add(decodeRow(rs));
                    else
                        v.add(decodeRow(rs, fieldList));
                    count++;
                } while ( (count<numRows||numRows<0) && rs.next() );
            }
            return (SysTbPropertiesBean[])v.toArray(new SysTbPropertiesBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    ///////////////////////////////////////////////////////////////////////
    // LISTENER
    ///////////////////////////////////////////////////////////////////////
    private SysTbPropertiesListener listener = null;

    /**
     * Registers a unique SysTbPropertiesListener listener.
     */
    //66.5
    public void registerListener(SysTbPropertiesListener listener) {
        this.listener = listener;
    }

    /**
     * Before the save of the SysTbPropertiesBean pObject.
     *
     * @param pObject the SysTbPropertiesBean pObject to be saved
     */
    //67
    void beforeInsert(SysTbPropertiesBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeInsert(pObject);
    }

    /**
     * After the save of the SysTbPropertiesBean pObject.
     *
     * @param pObject the SysTbPropertiesBean pObject to be saved
     */
    //68
    void afterInsert(SysTbPropertiesBean pObject) throws SQLException {
        if (listener != null)
            listener.afterInsert(pObject);
    }

    /**
     * Before the update of the SysTbPropertiesBean pObject.
     *
     * @param pObject the SysTbPropertiesBean pObject to be updated
     */
    //69
    void beforeUpdate(SysTbPropertiesBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeUpdate(pObject);
    }

    /**
     * After the update of the SysTbPropertiesBean pObject.
     *
     * @param pObject the SysTbPropertiesBean pObject to be updated
     */
    //70
    void afterUpdate(SysTbPropertiesBean pObject) throws SQLException {
        if (listener != null)
            listener.afterUpdate(pObject);
    }

    ///////////////////////////////////////////////////////////////////////
    // UTILS
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //2
    Manager getManager() {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    void freeConnection(Connection c) {
        getManager().releaseConnection(c); // back to pool
    }
    /**
     * Gets the connection.
     */
    Connection getConnection() throws SQLException {
        return getManager().getConnection();
    }

// class+ 

// class- 
}
